############# English navigation ##############
# main menu    
[[main]]
name = "Services"
URL = "services/"
weight = 2

[[main]]
name = "Themes"
URL = "themes/"
weight = 3

[[main]]
name = "Plans"
URL = "plans/"
weight = 4
  
[[main]]
name = "Contact"
URL = "contact/"
weight = 5

[[main]]
weight = 6
name = "More"
hasChildren = true

  [[main]]
  parent = "More"
  name = "About"
  URL = "about/"
  weight = 1

  [[main]]
  parent = "More"
  name = "FAQ"
  URL = "faq/"
  weight = 3

  #  [[main]]
  #  parent = "Pages"
  #  name = "Career"
  #  URL = "career/"
  
  #  [[main]]
  #  parent = "Pages"
  #  name = "Team"
  #  URL = "team/"

  #  [[main]]
  # name = "Blog"
  # URL = "blogs/"
  
  #  [[main]]
  #  parent = "Pages"
  #  name = "Changelog"
  #  URL = "changelog/"

#Footer menu
[[footer]]
name = "Company History"
URL = "about/"

[[footer]]
name = "About us"
URL = "about/"

[[footer]]
name = "Contact us"
URL = "contact/"

[[footer]]
name = "Services"
URL = "service/"

[[footer]]
name = "Privacy Policy"
URL = "#"