############# English navigation ##############
# main menu    
[[main]]
name = "Services"
URL = "services/"
weight = 2

[[main]]
name = "Designs"
URL = "designs/"
weight = 3

[[main]]
name = "Plans"
URL = "plans/"
weight = 4
  
[[main]]
name = "Contact"
URL = "contact/"
weight = 5

[[main]]
weight = 6
name = "More"
hasChildren = true

  [[main]]
  parent = "More"
  name = "About Us"
  URL = "about/"
  weight = 1
  
  [[main]]
  parent = "More"
  name = "Terms of Service"
  URL = "terms/"
  weight = 2

  # [[main]]
  # parent = "More"
  # name = "Plan Policy"
  # URL = "planpolicy/"
  # weight = 2

  #  [[main]]
  #  parent = "Pages"
  #  name = "Career"
  #  URL = "career/"
  
  #  [[main]]
  #  parent = "Pages"
  #  name = "Team"
  #  URL = "team/"

  #  [[main]]
  # name = "Blog"
  # URL = "blogs/"
  
  #  [[main]]
  #  parent = "Pages"
  #  name = "Changelog"
  #  URL = "changelog/"




#Footer menu

[[footer]]
name = "About Us"
URL = "about/"
weight = 1

[[footer]]
name = "Services"
URL = "services/"
weight = 2

# [[footer]]
# name = "FAQ"
# URL = "faq/"
# weight = 3

[[footer]]
name = "Contact Us"
URL = "contact/"
weight = 4

# [[footer]]
# name = "Plan Policy"
# URL = "planpolicy/"
# weight = 5

[[footer]]
name = "Terms of Service"
URL = "terms/"
weight = 5

[[footer]]
name = "Privacy Policy"
URL = "privacy/"
weight = 6